version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    container_name: backend
    working_dir: /app
    depends_on:
      - mysql_server

  mysql_server:
    build:
      context: .
      dockerfile: /database/Dockerfile
    container_name: mysql_server

    environment:
      - MYSQL_DATABASE=gepetto
      - MYSQL_USER=gepetto
      - MYSQL_PASSWORD=gepetto
      - MYSQL_ROOT_PASSWORD=gepetto

   