version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 81:80
    container_name: backend
    restart: unless-stopped
    working_dir: /app
    depends_on:
      - mysql_server

  mysql_server:
    build:
      context: .
      dockerfile: /database/Dockerfile
    ports:
      - 4321:3306
    container_name: mysql_server
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=gepetto
      - MYSQL_USER=gepetto
      - MYSQL_PASSWORD=gepetto
      - MYSQL_ROOT_PASSWORD=gepetto

   